name: 'Link Checker: Enterprise Cloud'

# **What it does**: This checks links for GHEC version of docs.
# **Why we have it**: We want to know if links break.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Setup node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: 'Link check: Enterprise Cloud'
        env:
          DOCS_VERSION: 'enterprise-cloud'
        run: npm run link-check
